name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        sudo apt update
        sudo apt install -y awscli

    - name: Send Files to EC2
      env:
        EC2_INSTANCE_ID: i-06a3fc62be664af42  # Replace with your EC2 instance ID
        AWS_REGION: us-east-1c  # Change if your instance is in a different region
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceids,Values=$EC2_INSTANCE_ID" \
          --parameters 'commands=["cd ~/ForestFire && git pull && python3 app.py"]' \
          --region $AWS_REGION
