name: Deploy ForestFire App to EC2

on:
  push:
    branches:
      - main  # Runs this workflow on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: 13.217.166.114
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -r -i private_key.pem * ec2-user@$EC2_HOST:~/ForestFire/
        ssh -i private_key.pem ec2-user@$EC2_HOST "cd ~/ForestFire && python3 app.py"
