name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up SSH Key
      run: |
        echo "$EC2_SSH_KEY" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to EC2
      env:
        EC2_HOST: 54.165.52.235
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem -r * ec2-user@$EC2_HOST:~/ForestFire/
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_HOST "cd ~/ForestFire && python3 app.py"
